### ISSUE TITLE
Personal problem

### ISSUE THREAD

**Issue by GevinGleb** [SandResidence/PingWheelBukkit#4]
Cannot understand how do I make it work. It should be .jar since its a plugin however there are only folder and 3 files. Help me please how can I make it work

**Comment by SandResidence** [comment]
These files are the source code of the pluin. You need to build it to get the JAR file.

**Comment by GevinGleb** [comment]
How do I build it? I dont know java or any other code language

**Comment by SandResidence** [comment]
I have just built it for you.
I will soon add a "Releases" tab where you can download the latest versions of the plugin.
[PingWheelBukkit.zip](https://github.com/SandResidence/PingWheelBukkit/files/12389348/PingWheelBukkit.zip)

**Comment by GevinGleb** [comment]
Thank you a lot! ♥
