### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by shayanz23** [SandResidence/PingWheelBukkit#5]
Hello, I have installed this plugin, but cant figure out the key combo or command needed to use it.

**Comment by SandResidence** [comment]
The plugin does not manage keybinds. The keybinds configuration can be found in the mod's settings.
This plugin simply listens to what the mod sends to the server, and then broadcasts it to all players.

**Comment by shayanz23** [comment]
oh, so I would also need the fabric mod on my own computer?

**Comment by SandResidence** [comment]
Yes. This plugin is the Bukkit implementation of that mod. Not a replacement.
